[package]
name = "cli-split-merge"
version = "1.1.0"
description = "CLI Split & Merge desktop utility"
authors = ["Simple Tools"]
edition = "2021"

[lib]
name = "cli_split_merge_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
calamine = "0.26"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }

lexical-core = "1"
ryu = "1"
itoa = "1"
memmap2 = "0.9"
memchr = "2"
rayon = "1.10"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
